---
- name: 1.系统初始化
  become: yes
  gather_facts: true
  hosts: all
  roles:
    - init
  tags: init

- name: 2.K8S 主机名
  become: yes
  gather_facts: true
  hosts: newnode
  roles:
    - hostname
  tags: hostname

- name: 3.部署Docker
  become: yes
  gather_facts: true
  hosts: newnode 
  roles:
    - docker 
  tags: docker

- name: 4.部署Containerd
  become: yes
  gather_facts: true
  hosts: newnode 
  roles:
    - containerd 
  tags: containerd

- name: 5.生成新token
  become: yes
  gather_facts: true
  hosts: master[0] 
  roles:
    - jointoken 
  tags: jointoken

- name: 6.部署K8S Node
  become: yes
  gather_facts: true
  hosts: newnode
  roles:
    - node
  tags: node
