- name: reload systemd
  become: yes
  command: systemctl daemon-reexec

- name: restart kubelet
  become: yes
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - kubelet
