---
- name: 创建临时目录
  become: yes
  file: dest={{ tmp_dir }} state=directory

- name: 创建 GPG 密钥目录
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: 下载 Kubernetes APT GPG 密钥
  become: yes
  apt_key:
    url: "{{ kube_gpg_key }}"

- name: 添加 Kubernetes APT 源
  apt_repository:
    repo: "{{ kube_repo }}"
    state: present
    filename: "kubernetes"

- name: 更新 APT 缓存
  become: yes
  apt:
    update_cache: yes

- name: 安装 kubelet-{{ kube_version }} kubeadm-{{ kube_version }} kubectl-{{ kube_version }}
  become: yes
  package:
    name:
      - "kubelet={{ kube_version }}"
      - "kubeadm={{ kube_version }}"
      - "kubectl={{ kube_version }}"
    state: present

- name: 删除默认的 kubeadm 二进制文件
  become: yes
  file:
    path: /usr/bin/kubeadm
    state: absent

- name: 拷贝二次修改的 kubeadm-{{ k8s_version }} 的二进制文件
  become: yes
  copy:
    src: "{{ tmp_dir }}/kubernetes/_output/local/go/bin/kubeadm"
    dest: /usr/bin/kubeadm
    mode: '0755'

- name: 设置kubectl自动补全给 ansible_user 和 root
  become: yes
  vars:
    kube_users: "{{ [ansible_user, 'root'] | unique }}"
    bash_lines:
      - "source /usr/share/bash-completion/bash_completion"
      - "source <(kubectl completion bash)"
  block:
    - name: 配置每个用户的 kubectl 自动补全
      lineinfile:
        path: "{{ '/root/.bashrc' if user == 'root' else '/home/' + user + '/.bashrc' }}"
        line: "{{ line }}"
        create: yes
        insertafter: EOF
        state: present
      loop: "{{ kube_users | product(bash_lines) | list }}"
      loop_control:
        label: "{{ item[0] }} -> {{ item[1] }}"
      vars:
        user: "{{ item[0] }}"
        line: "{{ item[1] }}"

- name: 生成init配置
  become: yes
  template:
    src: templates/kubeadm-init.conf.j2
    dest: "{{ tmp_dir }}/kubeadm-init.conf"
    mode: '0644'

- name: 修改 kubelet 存储目录
  become: yes
  template: src=kubelet.j2 dest=/etc/sysconfig/kubelet
  notify:
    - reload systemd
    - restart kubelet

- name: 创建 kubelet.service.d 目录
  become: yes
  file: 
    dest: /etc/systemd/system/kubelet.service.d
    state: directory

- name: 修改 cgroup 为 systemd
  become: yes
  template: src=10-kubeadm.conf.j2 dest=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  notify:
    - reload systemd
    - restart kubelet

- name: 重载 systemd 配置
  become: yes
  command: systemctl daemon-reexec

- name: 检查是否已经初始化（通过token.txt文件）
  become: yes
  stat:
    path: "{{ tmp_dir }}/token.txt"
  register: token_file_check

- name: 显示初始化状态
  debug:
    msg: "集群已初始化，跳过初始化步骤"
  when:
    - token_file_check.stat.exists

- name: kubeadm init 初始化 master 节点
  become: yes
  shell: "kubeadm init --config={{ tmp_dir }}/kubeadm-init.conf --upload-certs > {{ tmp_dir }}/token.txt"
  when: 
    - not token_file_check.stat.exists

- name: 设置 kubeconfig 给 ansible_user 和 root
  become: yes
  vars:
    kube_users: "{{ [ansible_user, 'root'] | unique }}"
  block:
    - name: 创建 kube config 目录
      become: yes
      file:
        path: "{{ (item == 'root') | ternary('/root/.kube', '/home/' + item + '/.kube') }}"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0700'
      loop: "{{ kube_users }}"
      when:
        - not token_file_check.stat.exists

    - name: 复制 kubeconfig 文件
      become: yes
      copy:
        src: "/etc/kubernetes/admin.conf"
        dest: "{{ (item == 'root') | ternary('/root/.kube/config', '/home/' + item + '/.kube/config') }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0600'
        remote_src: yes
      loop: "{{ kube_users }}"
      when:
        - not token_file_check.stat.exists

- name: 创建 master join 脚本
  become: yes
  shell: "grep -B2 ' --certificate-key' {{ tmp_dir }}/token.txt > {{ tmp_dir }}/master-join.sh"
  when:
    - not token_file_check.stat.exists

- name: 创建 node join 脚本
  become: yes
  shell: "grep -A1 'kubeadm join' {{ tmp_dir }}/token.txt |tail -2 > {{ tmp_dir }}/node-join.sh"
  when:
    - not token_file_check.stat.exists

- name: 等待 Kubernetes API 服务器准备好
  become: yes
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 6443
    state: started
    timeout: 300
  delegate_to: localhost
  register: kube_api_ready
  retries: 30
  delay: 5
  until: kube_api_ready is succeeded
