- name: 检查 hosts.bak 是否存在
  become: yes
  stat:
    path: /etc/hosts.bak
  register: backup_hosts

- name: 备份 /etc/hosts 如果未备份
  become: yes
  copy:
    src: /etc/hosts
    dest: /etc/hosts.bak
  when: not backup_hosts.stat.exists

- name: 添加 hosts
  become: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
